[book]
authors = ["Asociación de Estudiantes de Ingeniería en Computadores"]
language = "es"
multilingual = false
src = "src"
title = "ASEIC"
description = "Sitio web principal de ASEIC"

[output.html.fold]
enable = true
